### ISSUE TITLE
Resetting Eloqua Authentication Settings

### ISSUE THREAD

**Issue by alieneila** [solepixel/gravityforms-eloqua#1]
Not sure if this is happening for anyone else, however after setting the login credentials to link to the Eloqua account, I had mistyped my password. I saw the "Check here and update to reset" however after checking the box and updating, it doesn't reset and allow me to re-enter the login information. I have to completely remove all settings and reactivate the plugin to re-enter my login details.

Other than that, awesome job on this, saved me a LOT of time doing it myself lol.

**Comment by solepixel** [comment]
This is fixed in version 1.1.0, which will be released at the latest end of this week.
