### ISSUE TITLE
gravity form and eloqua

### ISSUE THREAD

**Issue by aledonofrio** [solepixel/gravityforms-eloqua#11]
Hello, We are trying to connect gravity form in worpress with eloqua using the plugin and we can't get passed the step where you need to set up the eloqua feed. Please, see the screenshot below: 
![image 1](https://cloud.githubusercontent.com/assets/23300486/20042362/8e76e3b0-a457-11e6-973b-b8d7d97e0075.png)

the dropdown list to select the form does not appear. 
I am using: 
![image](https://cloud.githubusercontent.com/assets/23300486/20042384/ea7e4ac2-a457-11e6-9fe5-3fd62ba38684.png)
![image](https://cloud.githubusercontent.com/assets/23300486/20042414/45ac9052-a458-11e6-8195-267b7ff18a7c.png)
Wordpress version: 4.5

Thanks for your help.

**Comment by JulianAlvarado** [comment]
Do you have the form created on the eloqua side? if yes have you check you api access is correct?

**Comment by aledonofrio** [comment]
Hello Julian, I am connecting with OAUTH from Gravity Forms to my eloqua account. The login works fine.
The form is already created on the eloqua side. When I try to configure the GF feed (under settings) the drop down that should appear does not appear and I can't get passed this step. I was not aware of any API configuration. What should I do/configure related to the API?
Thanks for your help!

**Comment by solepixel** [comment]
@aledonofrio What browser/OS are you using? Are you familiar with developer tools? They can be found in Chrome, Safari, and Firefox (not sure about Edge). If you [open developer tools](http://devtoolsecrets.com/secret/general-finding-the-development-tools.html) to the Console tab and reload the page, do you see any red error messages in the error console?

**Comment by baroquedesign** [comment]
Hello there,

Wondering if you can help with an issue I am having on a client's site.
The Gravity Form/Eloqua Plugin is communicating correctly with my Eloqua account, But when the form is submitted it brings up an error with no confirmations. Wondering if you know what might be happening.

Here is a page with the form we are testing.
http://ea2.92a.mwp.accessdomain.com/resources/case-studies


![gravity form error](https://cloud.githubusercontent.com/assets/25183822/22036732/575d1554-dca9-11e6-84eb-b738271bb440.png)


Thanks for your help,
Matt

**Comment by solepixel** [comment]
@aledonofrio @JulianAlvarado Please check out the latest version 1.6.0-delta:
https://github.com/solepixel/gravityforms-eloqua/releases/tag/1.6.0-delta
