### ISSUE TITLE
Activity Tracking

### ISSUE THREAD

**Issue by wtlunsford** [solepixel/gravityforms-eloqua#15]
I have the plugin installed and pushing contacts to Eloqua however, when a visitor submits a form I lose their tracking info. Based on the forms in Eloqua, each form requires 4 hidden fields and a specific form action. If I set up a form that uses that form action, it connects all the web activity to the contact. I'm not sure how to make that work using this plugin. Any assistance would be great.

**Comment by solepixel** [comment]
Can you take a look at Issue #9 and tell me if this is the same thing? If so, please comment on that issue with any additional information you have about these fields and I will try to get this feature added in. Otherwise, please describe these hidden fields here and I can look into those as well.

**Comment by wtlunsford** [comment]
Possibly. 
Eloqua is listing these as my required fields:
name="elqFormName" value="FORMNAME"
name="elqSiteID" value="SITEID"
name="elqCustomerGUID" value=""
name="elqCookieWrite" value="0"

But then also requires the following form action:
action="https://sSITEID.t.eloqua.com/e/f2"

The only thing visible that I see with the notifications that are sent back to me is the "URL of Form" value. I would much rather keep all my Gravity Forms than have to recreate all these.

**Comment by solepixel** [comment]
I remember seeing these when I first built this plugin and I think I had them in there originally, but then I realized that those form values are specific to the form action with the Eloqua provided forms. I'll double check when I have some time, but I think they only serve a purpose when using the embedded forms. With the GF Eloqua plugin, you can customize the submission data and action all with the settings. So if there's a URL parameter or cookie you'd like to pass to your form, you should be able to set those hidden fields up on each form. If you feel this is something that needs to be automatically integrated for every form connected to Eloqua, I can look deeper into it.

**Comment by wtlunsford** [comment]
I'm also in Birmingham so maybe we can talk through some of this and I can explain what all I'm looking at.

**Comment by ghost** [comment]
I am facing the same problem with this plugin.Unable to send elqCustomerGUID,elqCookieWrite hidden fields to Eloqua.Not able to map the hidden form fields with Eloqua fields.Here Eloqua only showing non-hidden fields.

Please find the attached screen shots for your reference
![form fields](https://user-images.githubusercontent.com/5596078/27223139-d74ffff0-52ac-11e7-8404-fd0a8f00d996.jpg)
![non-hidden](https://user-images.githubusercontent.com/5596078/27223140-d750895c-52ac-11e7-9d5c-3a061db13b15.jpg)



Can you please help me on this.

**Comment by solepixel** [comment]
@wtlunsford There is a new version (2.2.0) of my currently supported version of this plugin coming out very soon that will implement this feature. Check out https://briandichiara.com/product/gravityforms-eloqua/ for more details.
