### ISSUE TITLE
Eloqua disconnection happening regularly.

### ISSUE THREAD

**Issue by aaronware** [solepixel/gravityforms-eloqua#16]
Seems like the plugin disconnects pretty regularly (every few days). I see some pull requests but none of them appear to be related to the issue we are seeing.

**Comment by solepixel** [comment]
@aaronware I will be pushing a release shortly that includes additional debugging information in the disconnect email. This will hopefully shed some light on why disconnects are happening.

**Comment by aaronware** [comment]
@solepixel thanks for the almost instant response. Appreciate it!

**Comment by solepixel** [comment]
@aaronware I have recently discovered that the refresh token may not be working correctly, so I'm hoping to find a fix for that and will be in the next release.

**Comment by aaronware** [comment]
Thanks @solepixel for following up. If you need a hand with it let me know. @nate-allen or I can always fork and investigate it as well.

**Comment by solepixel** [comment]
I'll let you know. Any changes to the OAuth refresh token may or may not resolve the issue. There are still some instances where there is no information available why it's returning as disconnected. It may also require adding more items to the debugger log.

**Comment by Fridyboy** [comment]
Hi @solepixel , many thanks for your works. this plugin helped me so much.
but i found it cannot connect to Eloqua,  after i changed the IP address in my migration project.
i've tried to check the Eloqua white list settings, but it was working well.
after that, i've tried to change the login mode to HTTP, but it still crashes, and show me the tips 'invalid value', then i checked my input, all of them were correct.
for now i received 104 notified mail in this weekend, can you give me some suggestion, how can i fix this issue?

the below message always appear on my page ... __________________________________________________________________
`It seems as though Gravity Forms has lost connection to your Eloqua account. Click here to re-connect.`

**Comment by mattwatsoncodes** [comment]
Hi @solepixel, could this article be the solution? 

https://community.oracle.com/docs/DOC-1003687

"Starting with the 482 release, when you make a request to retrieve an Access token, you will receive a new refresh token each time. This refresh token should be used the next time a call is made to refresh the Access token."

**Comment by FixMiller** [comment]
Hello guys, just curios if there's been any update on this matter?
based on @mwtsn last comment there's no workaround for this.

**Comment by solepixel** [comment]
@mwtsn @FixMiller I will release an update to this soon that will try to utilize the newest Refresh Token per the documentation, however I actually spoke with one of the developers from Oracle at WordCamp US in Nashville, and was somewhat validated in that they know there are many problems with their API, especially with OAuth. His recommendation (for now) was to continue to use Basic Authentication until they have all the kinks worked out.

**Comment by solepixel** [comment]
@aaronware @Fridyboy @mwtsn @FixMiller Please take a look at the 1.6.0-delta release which fixes a bug related to the OAuth connection with Eloqua:
https://github.com/solepixel/gravityforms-eloqua/releases/tag/1.6.0-delta
