### ISSUE TITLE
Eloqua not connecting to account

### ISSUE THREAD

**Issue by baroquedesign** [solepixel/gravityforms-eloqua#17]
Hello,

So I recently migrated my Wordpress site from a staging host (http://ea2.92a.mwp.accessdomain.com) to my clients main host (http://changepoint.t4g.com). With this migration I am prompted to re-connect my Eloqua account to Gravity Forms. But when I go through the login process and hit "Accept" it stalls on a blank screen and won't connect.

Any ideas why this is happening on my migrated host and not on my staging host?
Any help would be very helpful. I can't figure out why this is happening.

<img width="1125" alt="screen shot 2017-02-22 at 10 35 03 am" src="https://cloud.githubusercontent.com/assets/25183822/23227011/7fefa1c6-f8ec-11e6-9323-69e2257e3395.png">

~ Matt

**Comment by solepixel** [comment]
@baroquedesign I would start by checking the server error logs. White screen usually means something broke, but errors aren't displayed. Try setting WP_DEBUG to true and WP_DEBUG_DISPLAY to false and WP_DEBUG_LOG to true, this will create a debug.log file in your wp-content folder which you can see what errors are occurring. More information on that here: https://codex.wordpress.org/Debugging_in_WordPress

On a side note, I'm hoping to resolve some OAuth related issues (with the refresh token) soon, and I will soon release an update with some bug fixes. That may also resolve your issue as well if it's related.

**Comment by baroquedesign** [comment]
Thank you for your quick response. I just received this PHP Error from my Host Admin.
Let me know if it means anything to you.

[Wed Feb 22 17:17:34.663929 2017] [php7:warn] [pid 2528:tid 1176] [client 10.20.58.61:65060] PHP Warning:  in_array() expects at least 2 parameters, 1 given in wp-content\\plugins\\gravityforms-eloqua-master\\gfeloqua.class.php on line 1672

**Comment by solepixel** [comment]
Try updating to the latest beta release and see if that resolves your
issue.

**Comment by baroquedesign** [comment]
Is that the 1.5.1 release?
I think that is the release I am using.

**Comment by solepixel** [comment]
@baroquedesign The release I'm referring to is 1.5.3-beta: https://github.com/solepixel/gravityforms-eloqua/releases/tag/1.5.3-beta

**Comment by solepixel** [comment]
@baroquedesign I'm closing this issue, but please review 1.6.0-delta if you're still having connectivity issues.
https://github.com/solepixel/gravityforms-eloqua/releases/tag/1.6.0-delta
