### ISSUE TITLE
Error Messages being thrown when I try to save. 

### ISSUE THREAD

**Issue by StephanieManley** [solepixel/gravityforms-eloqua#18]
I have written the form with Gravity Forms, then I have written the form in Eloqua, but when I try to connect them this is an error I receive.   

WordPress database error Table 'ctlien.wp_gf_addon_feed' doesn't exist for query SELECT id, form_id, addon_slug, meta FROM wp_gf_addon_feed WHERE is_active=1 AND form_id=2 AND addon_slug='gravityformseloqua' made by do_action('toplevel_page_gf_edit_forms'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, GFForms::forms, GFFormSettings::form_settings_page, do_action('gform_form_settings_page_gravityformseloqua'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, GFAddOn->form_settings_page, GFFeedAddOn->form_settings, GFEloqua->feed_edit_page, GFFeedAddOn->feed_edit_page, GFAddOn->render_settings, GFFeedAddOn->settings, GFAddOn->settings, GFAddOn->single_section, GFAddOn->single_setting_row, GFAddOn->single_setting, call_user_func, GFEloqua->settings_list_fields, GFAddOn->settings_field_map, GFAddOn->settings_field_map_select, GFAddOn::get_field_map_choices, GFFormsModel::get_entry_meta, apply_filters('gform_entry_meta'), WP_Hook->apply_filters, call_user_func_array, GFEloqua->add_success_meta, GFAPI::get_feeds

**Comment by richardW8k** [comment]
@StephanieManley The advice on the following page of the Gravity Forms documentation should create the missing database table: https://www.gravityhelp.com/documentation/article/forcing-gravity-forms-database-upgrades/

**Comment by solepixel** [comment]
@StephanieManley Did @richardW8k's comment resolve your issue?
