### ISSUE TITLE
disabled user in eloqua / gravity forms no longer submitting

### ISSUE THREAD

**Issue by L01sLan3** [solepixel/gravityforms-eloqua#19]
hi there- I disabled a user in eloqua and now forms are not submitting from my website. where is this info stored? Is it necessary to reinstall the plugin?

**Comment by solepixel** [comment]
You should be able to clear the user settings in WP Admin > Gravity Forms (Forms) > Settings > Eloqua. It will look like this: http://3cd.co/3M3B3K463f1i

Check the box then click update and you can change the stored user.

**Comment by L01sLan3** [comment]
Im receiving an error when I change to username. https://www.screencast.com/t/mbKOEiHG 

I can successfully log into eloqua - its a new user I created.

**Comment by L01sLan3** [comment]
think that was not a valid error. it appears to be working.
