### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by alieneila** [solepixel/gravityforms-eloqua#2]
Come across an issue, one form that only has a single field posts to Eloqua just fine. Another form with 20 fields the Eloqua response returns a 400 Bad Request error. All fields in Eloqua are marked as text fields and all fields are mapped in Gravity. Any ideas?

**Comment by solepixel** [comment]
I can't say anything for sure, however I've noticed some issues connecting to the API for the first time, for example when making an initial request via the API. Sometimes I get a request error, but the next time it does work. It may be related, but I'd have to do a bit more research about this issue.

**Comment by alieneila** [comment]
Ok, figured out the issue I believe. I think it has to do with a field that the client was using for the EloquaID capture, and to my understanding you haven't integrated the javascript/eloqua id capturing yet correct?
