### ISSUE TITLE
Plugin update 1.6.0

### ISSUE THREAD

**Issue by FredrickFloor** [solepixel/gravityforms-eloqua#20]
Hi there, on the 1.5.3 beta release u referred to the following update to 1.6.0.

Is this update still coming? Or did the development/maintenance of this plugin stop?

**Comment by solepixel** [comment]
Here is 1.6.0-delta. Please read the release notes about future versions.
https://github.com/solepixel/gravityforms-eloqua/releases/tag/1.6.0-delta
