### ISSUE TITLE
Question re "false positives" fixed in 1.5.0

### ISSUE THREAD

**Issue by ashaw953** [solepixel/gravityforms-eloqua#21]
Hi, Brian.  I am working with a customer that uses your Gravity forms plugin for Eloqua.  I was curious about the "false positives" that you addressed in 1.5.0.  The customer is seeing an issue that might conceivably be thought of as a false positive (a number of form submits incorrectly attributed to a campaign) so I thought I would find out what sort of false positives you tried to address in 1.5.0.  I don't at this point know what version of the plug-in they are using.  Just looking for information at this point.  Thanks,  Andy

**Comment by solepixel** [comment]
Hey @ashaw953, I believe the false positives were related to submissions that didn't make it over to Eloqua even though they were being reported to have been. It may not affect your issue, but try 1.6.0-delta and see if it helps:
https://github.com/solepixel/gravityforms-eloqua/releases/tag/1.6.0-delta
