### ISSUE TITLE
Gravity Forms Registration Warning

### ISSUE THREAD

**Issue by rickrussie** [solepixel/gravityforms-eloqua#4]
I get a warning on the plugins page that I have not registered Gravity Forms (It's registered). See screenshot.

Also note that I'm using version 1.1.0, but the version number wasn't updated in the core file so it displays as 1.0.1. 

Thank you so much for writing this plugin. It's really great!

![gf-registration-warning](https://cloud.githubusercontent.com/assets/852663/6495068/55e086e0-c28c-11e4-876f-a171f7981760.png)

**Comment by markryancreative** [comment]
I am having the same issue.

**Comment by solepixel** [comment]
I'm pushing up a new version that fixes this very shortly.
