### ISSUE TITLE
Eloqua API limit of 1000 items

### ISSUE THREAD

**Issue by ryanhellyer** [solepixel/gravityforms-eloqua#7]
The response at line 139 of the class.eloqua.api.php file is limited to exactly 1000 responses. This is causing problems when more than 1000 forms are required to be accessed.
`$response = $this->connection->request( $url, $args );`

I found this document which says that it is limited to 1000 by default, but that the limit can be increased.
https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCBB/Content/C_Tutorials/export-data-from-eloqua.htm

Do you know how to add that new limit argument to the API call? I tried add a query var to the URL, but that didn't work, and also tried altering the arguments via `$args['headers']` and `$args['limit']` but that didn't help.

If I can figure out how to modify the number of requests, I can add a filter and provide that as a pull request for you if that helps.

Thanks :)

**Comment by LimeCuda** [comment]
Hi Brian and Ryan, 

We're bumping into this exact same issue and have GF backend dropdown that pulls in 1000 of the forms but then cuts off before we can see our latest forms. 

We're digging in to see how this could be done. Any help or fixes would be much appreciated! 

Thanks!
Blake

**Comment by ryanhellyer** [comment]
I couldn't work out how it worked when I tried. If you can figure it out, I'd love how you do it :)

**Comment by solepixel** [comment]
Working on a solution for this, proposing to hit the API a few times when results come back as 1000 to attempt to retrieve the remainder of the forms, then store them in the transient until they are refreshed again. Looking at the documentation, I don't think there are any restrictions from getting forms over 1000, but I think each request is limited to 1000, so it just needs to be handled in multiple requests.

**Comment by LimeCuda** [comment]
We came up with a solution that seems to be working for at least getting the recent most 1000. The developer that came up with it is on medical leave. I'll see if I can get him to share it here. 

I think you are on exactly the right track and it sounds similar but better to what we did.

**Comment by BeardedGinger** [comment]
As a temporary solution to be able to access the additional forms, we modified the get_forms call to include the additional query args to access the second "page" of results.

Changing [line 189](https://github.com/solepixel/gravityforms-eloqua/blob/master/gravityforms-eloqua/api/class.eloqua.api.php#L189) of class.eloqua.api.php to:

`$call = 'assets/forms?count=1000&page=2/';`

**Comment by solepixel** [comment]
@ryanhellyer @LimeCuda @BeardedGinger Please review the changes I have made to this plugin and provide feedback regarding the number of forms that are being pulled in. I have added a recursive function that will load ALL Eloqua forms into the list. Source is here:
[class.eloqua.api.php - Line 188](https://github.com/solepixel/gravityforms-eloqua/blob/master/gravityforms-eloqua/api/class.eloqua.api.php#L188)

I could only fake test this since the only account I have access to only has ~244 forms. Everything should still cache in transients so if it loads slow, it should hopefully only be the first time.

**Comment by solepixel** [comment]
Closing this ticket due to no replies. If you're having issues with forms over 1000, please re-open with detail about the issue.
