### ISSUE TITLE
Hidden fields for customized data

### ISSUE THREAD

**Issue by JulianAlvarado** [solepixel/gravityforms-eloqua#9]
@solepixel 

Hi

There are several fields in Eloqua that I required to capture information but those are hidden. Im adding the respective fields:

TriggerType        = ‘BlogSub’, hidden
SourceSystem   = ’domain.com’, hidden
TrackIDMR          = TrackID of the campaign, hidden
DGIDMR              = DG tracking code for the campaign, hidden
TimeZone (optional) = GMT Offset, to send emails at optimal time, hidden
BrowserLocale (optional) = ISO2 default language, if available, for email, hidden
LanguagePref (optional) = ISO2 primary language if selected for email, hidden
 IPaddr (optional) = IPV4 or IPV6 address, hidden

I know there is a cookie to accomplish this, but is there any form to do it through the Eloqua integration with gravity forms?

**Comment by solepixel** [comment]
@JulianAlvarado I will see what I can find out about these fields. Thank you for providing this feedback!

**Comment by solepixel** [comment]
@JulianAlvarado I have implemented some of the Eloqua fields in the next release of Gravity Forms + Eloqua, available here: https://briandichiara.com/product/gravityforms-eloqua/. Will be released very soon!
